name: easy_pasta
description: A cross-platform clipboard manager for macOS, Linux and Windows, providing convenient copy and paste functionality.
publish_to: "none"
version: 2.1.0+1
package_name: com.harlans.easypasta.app
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  window_manager: ^0.4.3
  hotkey_manager: ^0.2.3
  super_clipboard: ^0.8.24
  tray_manager: ^0.3.1
  launch_at_startup: ^0.3.1
  package_info_plus: ^8.1.2
  intl: ^0.20.1
  flutter_html: ^3.0.0-beta.2
  flutter_highlight: ^0.7.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.4+4
  shared_preferences: ^2.3.4
  crypto: ^3.0.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
