name: build-mac-actions
on: [push]
run-name: ${{ github.actor }} is package mac app actions
jobs:
 build:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: x64
     - name: Restore packages
     - run: flutter pub get
     - name: Build App
     - run: flutter build macos
     - name: List files in the repository
     - run: ls ${{ github.workspace }}
     - run: echo "🍏 This job's status is ${{ job.status }}."
     - name: Publish Mac Artefacts
       uses: actions/upload-artifact@v1
       with:
        name: release-mac-app
        path: build/macos/Build/Products/Release